language: python
python:
  - "3.6"
install:
  - pip install tox
  - python setup.py install
script:
  - tox -e $(echo py$TRAVIS_PYTHON_VERSION | tr -d .)
  - {'add_script': 'y', 'cli_command_name': 'hathi_submission_workflow'} --pytest
