language: python
python:
- "3.6"
cache: pip
install:
- pip install -r requirements.txt
- pip install tox pyqt5
- make gui
- python setup.py install
script:
- tox -e $(echo py$TRAVIS_PYTHON_VERSION | tr -d .)
- hsw --pytest
