language: python
python:
- "3.6"
cache: pip
install:
- wget https://github.com/UIUCLibrary/pyhathiprep/archive/0.1.3.tar.gz && tar -xvzf 0.1.3.tar.gz
- cd pyhathiprep-0.1.3 && python setup.py install
- pip install git+git://github.com/UIUCLibrary/HathiValidate.git
- pip install git+git://github.com/UIUCLibrary/HathiZip.git
- pip install tox pyqt5
#- make gui
- python setup.py install
script:
- tox -e $(echo py$TRAVIS_PYTHON_VERSION | tr -d .)
